import { render, screen } from '@testing-library/react';

import Persons from '@/components/Persons';

// eslint-disable-next-line
jest.mock('next/image', () => () => <></>);

describe('Persons', () => {
  it('renders spinner', () => {
    render(<Persons isLoading={true} />);

    expect(screen.getByText('Loading...')).toBeInTheDocument();
  });

  it('renders persons', () => {
    const persons = [
      {
        id: 3223,
        name: 'Robert Downey Jr.',
        character: 'Tony Stark / Iron Man',
        birthday: '1965-04-04',
        profile_path: '/5qHNjhtjMD4YWH3UP0rm4tKwxCL.jpg',
        age: 56,
        ageOnRelease: 47,
      },
      {
        id: 16828,
        name: 'Chris Evans',
        character: 'Steve Rogers / Captain America',
        birthday: '1981-06-13',
        profile_path: '/3bOGNsHlrswhyW79uvIHH1V43JI.jpg',
        age: 40,
        ageOnRelease: 30,
      },
      {
        id: 103,
        name: 'Mark Ruffalo',
        character: 'Bruce Banner / The Hulk',
        birthday: '1967-11-22',
        profile_path: '/z3dvKqMNDQWk3QLxzumloQVR0pv.jpg',
        age: 53,
        ageOnRelease: 44,
      },
      {
        id: 74568,
        name: 'Chris Hemsworth',
        character: 'Thor Odinson',
        birthday: '1983-08-11',
        profile_path: '/jpurJ9jAcLCYjgHHfYF32m3zJYm.jpg',
        age: 37,
        ageOnRelease: 28,
      },
      {
        id: 1245,
        name: 'Scarlett Johansson',
        character: 'Natasha Romanoff / Black Widow',
        birthday: '1984-11-22',
        profile_path: '/6NsMbJXRlDZuDzatN2akFdGuTvx.jpg',
        age: 36,
        ageOnRelease: 27,
      },
      {
        id: 17604,
        name: 'Jeremy Renner',
        character: 'Clint Barton / Hawkeye',
        birthday: '1971-01-07',
        profile_path: '/ycFVAVMliCCf0zXsKWNLBG3YxzK.jpg',
        age: 50,
        ageOnRelease: 41,
      },
      {
        id: 91606,
        name: 'Tom Hiddleston',
        character: 'Loki',
        birthday: '1981-02-09',
        profile_path: '/mclHxMm8aPlCPKptP67257F5GPo.jpg',
        age: 40,
        ageOnRelease: 31,
      },
      {
        id: 2231,
        name: 'Samuel L. Jackson',
        character: 'Nick Fury',
        birthday: '1948-12-21',
        profile_path: '/mXN4Gw9tZJVKrLJHde2IcUHmV3P.jpg',
        age: 72,
        ageOnRelease: 63,
      },
      {
        id: 71189,
        name: 'Cobie Smulders',
        character: 'Maria Hill',
        birthday: '1982-04-03',
        profile_path: '/kgCkJEpeyAsQMMvVmgVM5Agh9Ww.jpg',
        age: 39,
        ageOnRelease: 30,
      },
      {
        id: 9048,
        name: 'Clark Gregg',
        character: 'Phil Coulson',
        birthday: '1962-04-02',
        profile_path: '/nbxFbr2SaF4Sdc6HdsF193GInvJ.jpg',
        age: 59,
        ageOnRelease: 50,
      },
      {
        id: 1640,
        name: 'Stellan Skarsgård',
        character: 'Erik Selvig',
        birthday: '1951-06-13',
        profile_path: '/x78BtYHElirO7Iw8bL4m8CnzRDc.jpg',
        age: 70,
        ageOnRelease: 60,
      },
      {
        id: 12052,
        name: 'Gwyneth Paltrow',
        character: 'Virginia "Pepper" Potts',
        birthday: '1972-09-27',
        profile_path: '/mYNPK8wgaHnYnR4LnKNYQf4Nhkx.jpg',
        age: 48,
        ageOnRelease: 39,
      },
      {
        id: 6162,
        name: 'Paul Bettany',
        character: 'J.A.R.V.I.S. (voice)',
        birthday: '1971-05-27',
        profile_path: '/vcAVrAOZrpqmi37qjFdztRAv1u9.jpg',
        age: 50,
        ageOnRelease: 40,
      },
      {
        id: 1214673,
        name: 'Alexis Denisof',
        character: 'The Other',
        birthday: '1966-02-25',
        profile_path: '/luTHwbaLutoKYWJSpk2WyuPasvk.jpg',
        age: 55,
        ageOnRelease: 46,
      },
      {
        id: 43553,
        name: 'Jerzy Skolimowski',
        character: 'Georgi Luchkov',
        birthday: '1938-05-05',
        profile_path: '/5yQ5GDNHTXrYrvT9ZcPk6VfrrgJ.jpg',
        age: 83,
        ageOnRelease: 74,
      },
      {
        id: 1479945,
        name: 'Kirill Nikiforov',
        character: 'Weaselly Thug',
        birthday: '1980-07-09',
        profile_path: '/694Bqo4C7sR6etcTyADUBcIc8He.jpg',
        age: 41,
        ageOnRelease: 31,
      },
      {
        id: 1479946,
        name: "M'laah Kaur Singh",
        character: 'Young Girl',
        birthday: '2002-12-22',
        profile_path: '/j2Bd3nvHCh7SqrnCDfL6UauvrUQ.jpg',
        age: 18,
        ageOnRelease: 9,
      },
      {
        id: 6280,
        name: 'Powers Boothe',
        character: 'World Security Council',
        birthday: '1948-06-01',
        profile_path: '/qk1KVY5N83MsO4Qvg4W1JA8SNFH.jpg',
        age: 73,
        ageOnRelease: 63,
      },
      {
        id: 14464,
        name: 'Jenny Agutter',
        character: 'World Security Council',
        birthday: '1952-12-20',
        profile_path: '/hxroyCTMk54hesfCRo4g6Jwc8dT.jpg',
        age: 68,
        ageOnRelease: 59,
      },
      {
        id: 60878,
        name: 'Warren Kole',
        character: 'Carrier Bridge Techs',
        birthday: '1977-09-23',
        profile_path: '/rwJHDXng0zn4QWhAP36tfhkXWjt.jpg',
        age: 43,
        ageOnRelease: 34,
      },
      {
        id: 81959,
        name: 'Alicia Sixtos',
        character: 'Carrier Bridge Techs',
        birthday: '1988-05-27',
        profile_path: '/4rUAzmYXQM5oFQ0lChuk7s7Api9.jpg',
        age: 33,
        ageOnRelease: 23,
      },
      {
        id: 1018947,
        name: 'Maximiliano Hernández',
        character: 'Jasper Sitwell',
        birthday: '1973-01-01',
        profile_path: '/cSlWqVimSVTtMv9GaI6WEPF38g3.jpg',
        age: 48,
        ageOnRelease: 39,
      },
      {
        id: 87128,
        name: 'Kenneth Tigar',
        character: 'German Old Man',
        birthday: '1942-09-24',
        profile_path: '/jgM0z7LUX5fOYkbKjZ1UVM6hcUb.jpg',
        age: 78,
        ageOnRelease: 69,
      },
      {
        id: 101522,
        name: 'Walter Perez',
        character: 'Shield Pilot',
        birthday: '1982-07-12',
        profile_path: '/57w97q9MQNv0Zxkaf8blO1xRjKQ.jpg',
        age: 39,
        ageOnRelease: 29,
      },
      {
        id: 5048,
        name: 'Harry Dean Stanton',
        character: 'Security Guard',
        birthday: '1926-07-14',
        profile_path: '/197UiLVdxPOv8196sqmUpJzOQB5.jpg',
        age: 95,
        ageOnRelease: 85,
      },
      {
        id: 1479957,
        name: 'Josh Cowdery',
        character: 'Maintenance Guy',
        birthday: '1978-01-01',
        profile_path: '/2gAoACv2mr31vjqspM9fHIe3MgP.jpg',
        age: 43,
        ageOnRelease: 34,
      },
      {
        id: 34486,
        name: 'Ashley Johnson',
        character: 'Waitress',
        birthday: '1983-08-09',
        profile_path: '/azeS7y73jaRcbAaQ6qAaCAdWenc.jpg',
        age: 37,
        ageOnRelease: 28,
      },
      {
        id: 2256,
        name: 'Robert Clohessy',
        character: 'Police Sergeant',
        birthday: '1958-06-10',
        profile_path: '/4f6F5F2pU4ng5NBAykagciSDqZT.jpg',
        age: 63,
        ageOnRelease: 53,
      },
      {
        id: 1224022,
        name: 'Enver Gjokaj',
        character: 'Police Officer',
        birthday: '1980-02-12',
        profile_path: '/1M3ISdFIaf4p1N3ZZTK7KnZwj9p.jpg',
        age: 41,
        ageOnRelease: 32,
      },
      {
        id: 1480045,
        name: 'Kelley Robins Hicks',
        character: 'Celebration Montage Interviewee',
        birthday: '1980-09-07',
        profile_path: '/poutoGBoAz8znML2v16DvF27q4w.jpg',
        age: 40,
        ageOnRelease: 31,
      },
      {
        id: 156342,
        name: 'Romy Rosemont',
        character: 'Shawna Lynde',
        birthday: '1964-10-28',
        profile_path: '/dzhrqpUa7W6lVjuigj0G28WrHQz.jpg',
        age: 56,
        ageOnRelease: 47,
      },
      {
        id: 19151,
        name: 'James Eckhouse',
        character: 'Senator Boynton',
        birthday: '1955-02-14',
        profile_path: '/iGG7iSZ5sBrmgkT9IHg1ipZCzgq.jpg',
        age: 66,
        ageOnRelease: 57,
      },
      {
        id: 1234512,
        name: 'Thomas Roberts',
        character: 'Himself',
        birthday: '1972-10-05',
        profile_path: '/uo8k9aGD3PHDPjXnsZF2E6eA3UD.jpg',
        age: 48,
        ageOnRelease: 39,
      },
      {
        id: 1480047,
        name: 'Pat Kiernan',
        character: 'Himself',
        birthday: '1968-01-01',
        profile_path: '/c8QASMhNim0bXySxaxRrkkzvKQ7.jpg',
        age: 53,
        ageOnRelease: 44,
      },
      {
        id: 19137,
        name: 'Lou Ferrigno',
        character: 'Hulk (voice - uncredited)',
        birthday: '1951-11-09',
        profile_path: '/obTtRrm8EbDzuiKpLjAd9s1i9v5.jpg',
        age: 69,
        ageOnRelease: 60,
      },
      {
        id: 66525,
        name: 'Jesse Garcia',
        character: 'Carrier Bridge Techs',
        birthday: '1982-01-01',
        profile_path: '/jsEZz7z1wI95277m7S9YM1dbVYb.jpg',
        age: 39,
        ageOnRelease: 30,
      },
      {
        id: 1153698,
        name: 'Ricardo Andres',
        character: 'Lentil Merchant (uncredited)',
        birthday: '1950-10-06',
        profile_path: '/sbce6eUbj8UKH0EJhDgIV4SprxZ.jpg',
        age: 70,
        ageOnRelease: 61,
      },
      {
        id: 1191953,
        name: 'Mayank Bhatter',
        character: 'Celebration Montage Man Shaving Beard (uncredited)',
        birthday: '1987-06-10',
        profile_path: '/caE4ZU2W5eKlitJv5EvnxhGhpE6.jpg',
        age: 34,
        ageOnRelease: 24,
      },
      {
        id: 1480060,
        name: 'Eric Frank',
        character: 'Stuttgart Citizen (uncredited)',
        birthday: '1977-03-05',
        profile_path: null,
        age: 44,
        ageOnRelease: 35,
      },
      {
        id: 1480087,
        name: 'Demoine Kinney',
        character: 'S.H.I.E.L.D. Agent (uncredited)',
        birthday: '1985-10-20',
        profile_path: null,
        age: 35,
        ageOnRelease: 26,
      },
      {
        id: 1001496,
        name: 'Sean Meehan',
        character: 'Guard (uncredited)',
        birthday: '1974-12-24',
        profile_path: null,
        age: 46,
        ageOnRelease: 37,
      },
      {
        id: 1365516,
        name: 'Martin Palmer',
        character: 'Shiel Employee (uncredited)',
        birthday: '1959-11-04',
        profile_path: null,
        age: 61,
        ageOnRelease: 52,
      },
      {
        id: 1480202,
        name: 'Frank Powers',
        character: 'S.H.I.EL.D Agent - Loki Escort (uncredited)',
        birthday: '1975-07-16',
        profile_path: null,
        age: 46,
        ageOnRelease: 36,
      },
      {
        id: 1480204,
        name: 'Brent Reichert',
        character: 'Stuttgart Gala Patron (uncredited)',
        birthday: '1971-05-09',
        profile_path: null,
        age: 50,
        ageOnRelease: 40,
      },
      {
        id: 1454362,
        name: 'Gina Sarno',
        character: 'Restaurant Patron (uncredited)',
        birthday: '1989-05-24',
        profile_path: null,
        age: 32,
        ageOnRelease: 22,
      },
      {
        id: 1673576,
        name: 'Alex DeCourville',
        character: 'Tourist (uncredited)',
        birthday: '1988-01-01',
        profile_path: '/97TmbMkAtGWe15ANftMZaMrSLYX.jpg',
        age: 33,
        ageOnRelease: 24,
      },
      {
        id: 1376001,
        name: 'Tina Grimm',
        character: 'NYC Pedestrian (uncredited)',
        birthday: '1982-02-19',
        profile_path: '/utRFgwBWqyM2k4nMki9F15hFOeS.jpg',
        age: 39,
        ageOnRelease: 30,
      },
    ];
    render(<Persons isLoading={false} persons={persons} />);

    expect(screen.getAllByTestId('name')).toHaveLength(persons.length);
  });
});
